betomax_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from ecoapp import urls as api_urls


urlpatterns = [
    url(r'^api/', include(api_urls)),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'', include('ecoapp.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

ecoapp/urls.py
from .views import (base_view, about_view, contact_view,
                    transport_view, login, registration,
                    ProductList, ProductDetail, map_view)
from django.contrib.auth.views import logout
from django.conf import settings

from ecoapp.views import *
from rest_framework.routers import DefaultRouter
from django.conf.urls import url, include
from rest_framework_jwt.views import obtain_jwt_token

router = DefaultRouter()
router.register(r'products', ProductsApiView)

urlpatterns = [

    url(r'^api_shop/', include(router.urls)),
    url(r'^auth_api/', obtain_jwt_token),
    url(r'^feedbacks/', feedbacks, name='feedback'),
    url(r'^personal/', personal_cabinet, name='personal'),
    url(r'^maps/', map_view),
    url(r'^shops/', ProductList, name='shops'),
    url(r'^about_us', about_view, name='about_us'),
    url(r'^contacts', contact_view, name='contact_us'),
    url(r'^transport', transport_view, name='transport'),
    url(r'^register/', registration, name='register'),
    url(r'^auth/login/$', login),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^$', base_view, name='base'),
    url(r'^(?P<category_slug>[-\w]+)/$', ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProductDetail, name='ProductDetail'),

]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.AdminOrderPDF, name='AdminOrderPDF')
]

cart/models.py
from django.db import models

orders/models.py
from django.db import models
from ecoapp.models import Product


class Order(models.Model):
    first_name = models.CharField(verbose_name='Имя', max_length=50)
    last_name = models.CharField(verbose_name='Фамилия', max_length=50)
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(verbose_name='Адрес', blank=True, max_length=250)
    postal_code = models.CharField(verbose_name='Почтовый код', max_length=20)
    city = models.CharField(verbose_name='Город', max_length=100)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Обновлен', auto_now=True)
    paid = models.BooleanField(verbose_name='Оплачен', default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ: {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    product = models.ForeignKey(Product, related_name='order_items')
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code',
                  'city']
        widgets = {'address': forms.HiddenInput(attrs={"placeholder": 'Адрес доставки'})}

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ecoapp.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart.html', {'cart': cart})

ecoapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, RentaCar, OrderBeton, PersonalOrder, ProductsWholesale, Excursion, Contacts, \
    Comments, Feedbacks, UserProfile
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.views import login as original_login
from decimal import Decimal
from .forms import (RegisterForm, RentaCarForm, BetonOrdersForm,
                    PersonalOrderForm, ProductWholesaleForm, ExcursionForm,
                    ContactsForm, CommentsForm, FeedbacksForm, UserProfileSignupForm,
                    UserUpdateForm, AvatartUpdateForm)
from cart.forms import CartAddProductForm
from .serializers import ProductSerializers
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import GenericViewSet, mixins
from django.db import transaction
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


@login_required
def personal_cabinet(request):
    user = User.objects.filter(username=request.user)
    user_profile = UserProfile.objects.filter(user=request.user)
    if request.method == "POST":
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        user_update_avatar = AvatartUpdateForm(request.POST, instance=request.user.userprofile)
        change_password = PasswordChangeForm(request.user, request.POST)
        if user_update_form.is_valid() and user_update_avatar.is_valid():
            user_update_form.save()
            user_update_avatar.save()
            messages.success(request, f'Ваш профиль успешно обновлен')
        else:
            messages.error(request, f'Пожалуйста исправьте ошибки')
        if change_password.is_valid():
            user = change_password.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, f'Ваш пароль успешно изменен')
        else:
            messages.error(request, f'Исправьте ошибки')
    else:
        user_update_form = UserUpdateForm(instance=request.user)
        user_update_avatar = AvatartUpdateForm(instance=request.user.userprofile)
        change_password = PasswordChangeForm(request.user)
    return render(request, 'personal_cabinet.html', {'context': user, 'avatar': user_profile,
                                                     'update_user_form': user_update_form,
                                                     'update_avatar': user_update_avatar,
                                                     'change_password': change_password})


def map_view(request):
    return render(request, 'maps.html')


def feedbacks(request):
    if request.method == "POST":
        feedback_form = FeedbacksForm(request.POST)
        if feedback_form.is_valid():
            name = feedback_form.cleaned_data.get("name")
            phone = feedback_form.cleaned_data.get("phone")
            feed = Feedbacks(name=name, phone=phone)
            feed.save()
            return HttpResponseRedirect('/')
    else:
        feedback_form = FeedbacksForm()
    return HttpResponseRedirect('/')


def base_view(request):
    if request.method == 'POST':
        renta_form = RentaCarForm(request.POST)
        beton_form = BetonOrdersForm(request.POST)
        personal_form = PersonalOrderForm(request.POST, request.FILES)
        wholesales_form = ProductWholesaleForm(request.POST)
        excursion_form = ExcursionForm(request.POST)
        if renta_form.is_valid():
            fio_renta = renta_form.cleaned_data.get('fio_renta')
            phone_renta = renta_form.cleaned_data.get('phone_renta')
            rents = RentaCar(fio_renta=fio_renta, phone_renta=phone_renta)
            rents.save()
        if beton_form.is_valid():
            fio_beton = beton_form.cleaned_data.get('fio_beton')
            phone_beton = beton_form.cleaned_data.get('phone_beton')
            betons = OrderBeton(fio_beton=fio_beton, phone_beton=phone_beton)
            betons.save()
        if personal_form.is_valid():
            fio_personal = personal_form.cleaned_data.get('fio_personal')
            phone_personal = personal_form.cleaned_data.get('phone_personal')
            image_personal = personal_form.cleaned_data.get('image_personal')
            personal_order = PersonalOrder(fio_personal=fio_personal, phone_personal=phone_personal,
                                           image=image_personal)
            personal_order.save()
        if wholesales_form.is_valid():
            fio_wholesale = wholesales_form.cleaned_data.get('fio_wholesale')
            phone_wholesale = wholesales_form.cleaned_data.get('phone_wholesale')
            wholesales = ProductsWholesale(fio_wholesales=fio_wholesale, phone_wholesales=phone_wholesale)
            wholesales.save()
        if excursion_form.is_valid():
            name_university = excursion_form.cleaned_data.get('name_university')
            fio_excursion = excursion_form.cleaned_data.get('fio_excursion')
            number_students = excursion_form.cleaned_data.get('number_students')
            phone_excursion = excursion_form.cleaned_data.get('phone_excursion')
            excursion = Excursion(name_university=name_university, fio_excursion=fio_excursion,
                                  number_students=number_students, phone_excursion=phone_excursion)
            excursion.save()
    else:
        renta_form = RentaCarForm()
        beton_form = BetonOrdersForm()
        personal_form = PersonalOrderForm()
        wholesales_form = ProductWholesaleForm()
        excursion_form = ExcursionForm()
    return render(request, 'base.html', {'renta_form': renta_form, 'beton_form': beton_form,
                                         'personal_form': personal_form, 'wholesales_form': wholesales_form,
                                         'excursion_form': excursion_form})


# Страница с товарами
def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shops.html', {
        'category': category,
        'categories': categories,
        'products': products
    })


# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    com = Comments.objects.filter(product=product)
    category = Category.objects.all()
    products = Product.objects.filter(available=True)
    prod = products.filter(category=category)[:5]

    if request.method == "POST":
        comments_form = CommentsForm(request.POST)
        if comments_form.is_valid():
            name = comments_form.cleaned_data.get('name')
            email = comments_form.cleaned_data.get('email')
            comment = comments_form.cleaned_data.get('comment')
            com_save = Comments(product=product, name=name, email=email, comment=comment)
            com_save.save()
    else:
        comments_form = CommentsForm()
    return render(request, 'product.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'comments_form': comments_form, 'coments': com,
                   'prod': prod})


def about_view(request):
    return render(request, 'about_us.html')


def contact_view(request):
    if request.method == "POST":
        contact_form = ContactsForm(request.POST)
        if contact_form.is_valid():
            fio_contact = contact_form.cleaned_data.get('fio_contacts')
            phone_contacts = contact_form.cleaned_data.get('phone_contacts')
            questions_contacts = contact_form.cleaned_data.get('questions_contacts')
            contact = Contacts(fio_contacts=fio_contact, phone_contacts=phone_contacts,
                               questions_contacts=questions_contacts)
            contact.save()
    else:
        contact_form = ContactsForm()
    return render(request, 'contact_us.html', {'contact_form': contact_form})


def transport_view(request):
    return render(request, 'transport.html')


def change_item_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart_item.qty = int(qty)
    cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
    cart_item.save()
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({
        'cart_total': cart.items.count(),
        'item_total': cart_item.item_total,
        'cart_total_price': cart.cart_total,
    })


def registration(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        user_profile_signup_form = UserProfileSignupForm(request.POST, request.FILES)
        if form.is_valid() and user_profile_signup_form.is_valid():
            with transaction.atomic():
                user = form.save()
                user_profile = user_profile_signup_form.save(commit=False)
                user_profile.user = user
                user_profile.save()
                username = form.cleaned_data.get('username')

orders/views.py
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import OrderCreated
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint
from .models import Order


def AdminOrderPDF(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('pdf.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=order_{}.pdf'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + '/css/bootstrap.min.css',)])
    return response


def OrderCreate(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            OrderCreated.delay(order.id)
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))
            # return render(request, 'bill_page.html', {'order': order})

    form = OrderCreateForm()
    return render(request, 'checkout.html', {'cart': cart, 'form': form})

ecoapp/templates/bill_page.html
{% extends 'base.html' %}
{% block title %}
  Спасибо за заказ
{% endblock %}

{% block content %}
    <div class="thanks">
          <h1>Спасибо за заказ</h1>
          <p>Идентификатор вашего заказа: {{ order.id }}</p>
    </div>

{% endblock %}

ecoapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>

    	#map {
            width: 100%;
            height: 300px;
            padding: 0;
            margin: 0;
        }
 .ymaps-2-1-63-gotoymaps{
    display:none!important;
    }
#result{display: none;background: #fff;}
#result.active{display: block;}

	</style>
    <main id="mt-main">
        <section class="mt-contact-banner mt-banner-22 wow fadeInUp" data-wow-delay="0.4s"
                 style="background-image: url({% static 'img/shoping_cart_bg.jpg'%});">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <h1 class="text-center">Ваша корзина</h1>
                <!-- Breadcrumbs of the Page -->
                <!-- Breadcrumbs of the Page end -->
              </div>
            </div>
          </div>
        </section>

        <!-- Mt Process Section of the Page -->
        <div class="my-cart mt-process-sec wow fadeInUp" data-wow-delay="0.4s">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <ul class="list-unstyled process-list">
                  <li class="active">
                    <span class="counter">01</span>
                    <strong class="title">Корзина</strong>
                  </li>
                  <li>
                    <span class="counter">02</span>
                    <strong class="title">Оформление заказа</strong>
                  </li>
                  <li>
                    <span class="counter">03</span>
                    <strong class="title">Оплата</strong>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div><!-- Mt Process Section of the Page end -->
        <!-- Mt Product Table of the Page -->
        <div class="mt-product-table wow fadeInUp" data-wow-delay="0.4s">
          <div class="container">

            <div class="row border">
                <div class="col-xs-12 col-sm-6">
                <strong class="title">Продукт</strong>
              </div>
              <div class="col-xs-12 col-sm-2">
                <strong class="title">Цена</strong>
              </div>
              <div class="col-xs-12 col-sm-2">
                <strong class="title">Количество</strong>
              </div>
              <div class="col-xs-12 col-sm-2">
                <strong class="title">Итого</strong>
              </div>
            </div>
               {% for item in cart %}
            {% with product=item.product %}
            <div class="row border">
              <div class="col-xs-12 col-sm-2">
                <div class="img-holder">
                  <img src="{{ product.image.url }}" alt="image description">
                </div>
              </div>
              <div class="col-xs-12 col-sm-4">
                <strong class="product-name">{{ product.name }}</strong>
              </div>
              <div class="col-xs-12 col-sm-2">
                <strong class="price" style="font-size: 16px!important;">{{ item.price }} руб.</strong>
              </div>
              <div class="col-xs-12 col-sm-2">
                   <form style="margin-top: -8%;" class="qyt-form"  action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <button style="margin-top: -4%;" class="btn btn-success" type="submit"><i class="fa fa-refresh"></i></button>
              </form>
              </div>
              <div class="col-xs-12 col-sm-2">
                <strong class="price" id="prices" style="font-size: 16px!important;">{{ item.total_price }}  руб.</strong>
                 <a href="{% url "cart:CartRemove" product.id %}"><i class="fa fa-close"></i></a>
              </div>
            </div>
              {% endwith %}
          {% endfor %}

        </div><!-- Mt Product Table of the Page end -->
        <!-- Mt Detail Section of the Page -->
        <section class="mt-detail-sec style1 wow fadeInUp" data-wow-delay="0.4s">
          <div class="container">
            <div class="row">
              <div class="col-xs-12 col-sm-6">
                <h2>Рассчитать Доставку</h2>
                <form action="#" class="bill-detail">
                  <fieldset>
                    <div class="form-group">
                        <input  class="form-control" type="text" value="г.Ташкент Охангабо, 7" readonly>
                    </div>
                    <div class="form-group">
                      <div id="map"></div>
                    </div>
                    <div class="form-group">
                      <button id="calc" class="process-btn" type="submit">Рассчитать доставку<i class="fa fa-calculator"></i></button>
                    </div>
                  </fieldset>
                </form>
              </div>

              <div class="col-xs-12 col-sm-6">

                <h2>Итого: {{ cart.get_total_price }}</h2>

                <ul class="list-unstyled block cart">
                  <li>
                    <div class="txt-holder">
                      <strong class="title sub-title pull-left">Итого без доставки</strong>
                      <div class="txt pull-right">
                        <span id="cart-total-price">{{ cart.get_total_price }}</span>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="txt-holder">
                      <strong class="title sub-title pull-left">Доставка</strong>
                      <div class="txt pull-right"  id="result">
                      </div>
                    </div>
                  </li>
                  <li style="border-bottom: none;">
                    <div class="txt-holder">
                      <strong class="title sub-title pull-left">Итоговая цена:</strong>
                      <div class="txt pull-right">
                        <span id="cart-total-price"> {{ cart.cart_total }}</span>
                      </div>
                    </div>
                  </li>
                </ul>

                  <a href="{% url "orders:OrderCreate" %}" class="process-btn">Оформить заказ <i class="fa fa-check"></i></a>
              </div>
            </div>
          </div>
        </section>
        <!-- Mt Detail Section of the Page end -->


      </main><!-- Main of the Page end here -->





  		<script>
					$('#calc').on('click',function(){
			$('#result').addClass('active');
		});
		function init() {
		    var myMap = new ymaps.Map('map', {
		            center: [60.906882, 30.067233],
		            zoom: 9,
		            type: 'yandex#map',
		            visible:false,
		            controls: []

		        }),
		        searchStartPoint = new ymaps.control.SearchControl({
		            options: {
		                useMapBounds: true,
		                noPlacemark: true,
		                noPopup: true,
		                visible: false,
		                // value: 'test',
		                placeholderContent: 'Адрес начальной точки',
		                size: 'large'
		            }
		        }),

		        searchFinishPoint = new ymaps.control.SearchControl({
		            options: {
		                useMapBounds: true,
		                noCentering: true,
		                noPopup: true,
		                noPlacemark: true,
		                placeholderContent: 'Адрес конечной точки',
		                size: 'large',
		                float: 'none',
		                position: { left: 10, top: 44 }
		            }
		        }),
		        calculator = new DeliveryCalculator(myMap, myMap.getCenter());
		        		        searchStartPoint.search('>Узбекистан, Ташкент, Тошкент Халка Автомобиль Йули');
		    myMap.controls.add(searchStartPoint);
		    myMap.controls.add(searchFinishPoint);

		    searchStartPoint.events.add('resultselect', function (e) {
		        var results = searchStartPoint.getResultsArray(),
		            selected = e.get('index'),
		            point = results[selected].geometry.getCoordinates();

		        calculator.setStartPoint(point);
		    })
		        .add('load', function (event) {
		            // По полю skip определяем, что это не дозагрузка данных.
		            // По getRusultsCount определяем, что есть хотя бы 1 результат.
		            if (!event.get('skip') && searchStartPoint.getResultsCount()) {
		                searchStartPoint.showResult(0);
		            }
		        });

		    searchFinishPoint.events.add('resultselect', function (e) {
		        var results = searchFinishPoint.getResultsArray(),
		            selected = e.get('index'),
		            point = results[selected].geometry.getCoordinates();

		        calculator.setFinishPoint(point);
		    })
		        .add('load', function (event) {
		            // По полю skip определяем, что это не дозагрузка данных.
		            // По getRusultsCount определяем, что есть хотя бы 1 результат.
		            if (!event.get('skip') && searchFinishPoint.getResultsCount()) {
		                searchFinishPoint.showResult(0);
		            }
		        });
		}

		function DeliveryCalculator(map, finish) {
		    this._map = map;
		    this._start = null;
		    this._route = null;
		    this._startBalloon;
		    this._finishBalloon;

		    map.events.add('click', this._onClick, this);
		}

		var ptp = DeliveryCalculator.prototype;

		ptp._onClick= function (e) {
		    if (this._start) {
		        this.setFinishPoint(e.get('coords'));
		    } else {
		        this.setStartPoint(e.get('coords'));
		    }
		};

		ptp._onStartDragEnd = function (e) {
		    var coords = this._start.geometry.getCoordinates();
		    this.geocode("start", coords);
		}

		ptp._onFinishDragEnd = function (e) {
		    var coords = this._finish.geometry.getCoordinates();
		    this.geocode("finish", coords);
		}

		ptp.getDirection = function () {
		    if(this._route) {
		        this._map.geoObjects.remove(this._route);
		    }

		    if (this._start && this._finish) {
		        var self = this,
		            start = this._start.geometry.getCoordinates(),
		            finish = this._finish.geometry.getCoordinates(),
		            startBalloon = this._startBalloon,
		            finishBalloon = this._finishBalloon;
		        ymaps.route([start, finish])
		            .then(function (router) {
		                var distance = Math.round(router.getLength() / 1000),
		                    message = '<span style="font-weight: bold; font-style: italic">Стоимость доставки: %sс.</span>';

		                self._route = router.getPaths();

		                self._route.options.set({ strokeWidth: 5, strokeColor: '0000ffff', opacity: 0.5 });
		                self._map.geoObjects.add(self._route);
		                self._start.properties.set('balloonContentBody', startBalloon + message.replace('%s', self.calculate(distance)));
		                self._finish.properties.set('balloonContentBody', finishBalloon + message.replace('%s', self.calculate(distance)));
		                $('#result').html(finishBalloon + message.replace('%s', self.calculate(distance)));
		            });

		        self._map.setBounds(self._map.geoObjects.getBounds())
		    }
		};

		ptp.setStartPoint = function (position) {
		    if(this._start) {
		        this._start.geometry.setCoordinates(position);
		    }
		    else {
		        this._start = new ymaps.Placemark(position, { iconContent: 'А' }, { draggable: true });
		        this._start.events.add('dragend', this._onStartDragEnd, this);
		        this._map.geoObjects.add(this._start);
		    }
		    this.geocode("start", position);
		};

		ptp.setFinishPoint = function (position) {
		    if(this._finish) {
		        this._finish.geometry.setCoordinates(position);
		    }
		    else {
		        this._finish = new ymaps.Placemark(position, { iconContent: 'Б' }, { draggable: true });
		        this._finish.events.add('dragend', this._onFinishDragEnd, this);
		        this._map.geoObjects.add(this._finish);
		    }
		    if (this._start) {
		        this.geocode("finish", position);
		    }
		};

		ptp.geocode = function (str, point) {
		    ymaps.geocode(point).then(function(geocode) {
		        if (str == "start") {
		            this._startBalloon = geocode.geoObjects.get(0) &&
		                geocode.geoObjects.get(0).properties.get('balloonContentBody') || '';
		            console.log(str + "" + this._startBalloon);
		        } else {
		            this._finishBalloon = geocode.geoObjects.get(0) &&
		                geocode.geoObjects.get(0).properties.get('balloonContentBody') || '';
		            console.log(str + " " + this._finishBalloon);
		        }
		        this.getDirection();
		    }, this);

		}
		ptp.calculate = function (len) {
		    // Константы.
		    var DELIVERY_TARIF = 150000,
		        MINIMUM_COST = 95000;

		    return Math.max(len * DELIVERY_TARIF, MINIMUM_COST);
		};

		ymaps.ready(init);



		</script>
{% endblock content %}